driver:
  name: vagrant
  # network:
  #  - ["public_network", { bridge: 'en0: Ethernet' } ]
  #  - ["public_network", { bridge: 'en1: Wi-Fi (AirPort)' } ]

provisioner:
  name: chef_zero
  data_path: test/fixtures

platforms:
  - name: centos-6.7
    driver_config:
      customize:
        memory: 1024
  - name: centos-7.2
    driver_config:
      customize:
        memory: 1024
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    driver_config:
      customize:
        memory: 1024
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
    driver_config:
      customize:
        memory: 1024

  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
    driver_config:
      customize:
        memory: 1024

suites:
  - name: general
    run_list:
      - recipe[netdata]

  - name: general-chef12
    run_list:
      - recipe[netdata]
    provisioner:
      require_chef_omnibus: '12.20.3'
